export const CLIENTE_CONSTANTES = {
    START_OBTER_CLIENTES : "START_OBTER_CLIENTES",
    CLIENTES_OBTIDOS : "CLIENTES_OBTIDOS",
    ADD_CLIENTE:"ADD_CLIENTE",
    EDITAR_CLIENTE:"EDITAR_CLIENTE",
    TOGGLE_MODAL:"TOGGLE_MODAL",
    ENDERECO_POR_CEP_DIGITADO:"ENDERECO_POR_CEP_DIGITADO"
}