export const CLIENTE_CONSTANTES = {
    START_OBTER_CLIENTES : "START_OBTER_CLIENTES",
    CLIENTES_OBTIDOS : "CLIENTES_OBTIDOS",
    TOGGLE_MODAL:"TOGGLE_MODAL",
    EDITAR_CLIENTE:"EDITAR_CLIENTE"
}